### ISSUE TITLE
received signal SIGSEGV, Segmentation fault

### ISSUE THREAD

**Issue by khantaena** [khantaena/headunit#1]
(gdb) Thread 1 "headunit" received signal SIGSEGV, Segmentation fault.
Invalid thread ID: 1 "headunit" received signal SIGSEGV, Segmentation fault.
(gdb) 0x00007ffff699f16c in BIO_write () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
Undefined command: "0x00007ffff699f16c".  Try "help".
(gdb) (gdb) bt
Undefined command: "".  Try "help".
(gdb) #0  0x00007ffff699f16c in BIO_write () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
(gdb) #1  0x000000000040546d in iaap_recv_dec_process (chan=2, flags=11, 
(gdb)     buf=0x7183a4 <rx_buf+9220> "\027\003\003%\221^|\326\031)R\226\261\245g\347\376\313\310C\245\070\352\375\230c\277\023\212ROb+\217\270\023ٵ\004f\237\372)\034z\246$\235\nҸ\201_\213\363\v\030\302\375\254q\331\375\023\306\301&,\020\024\177ζX,\200g\307\363:\336\016\271\204\363\nM\004", len=9622) at ../jni/hu_aap.c:1256
Undefined command: "buf".  Try "help".
(gdb) #2  0x0000000000405749 in hu_aap_recv_process () at ../jni/hu_aap.c:1411
(gdb) #3  0x0000000000408e4e in read_data (app=0x71a720 <gst_app>) at main.c:63
(gdb) #4  0x00007ffff71aefda in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) #5  0x00007ffff71af380 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) #6  0x00007ffff71af6a2 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) #7  0x000000000040ab21 in gst_loop (app=0x71a720 <gst_app>) at main.c:806
(gdb) #8  0x000000000040afa7 in main (argc=1, argv=0x7fffffffe538) at main.c:974

**Comment by khantaena** [comment]
fixed : #70ba706bd079f4b6d3f8e643f8b9fc2edc170c13
http://stackoverflow.com/questions/22152955/what-is-causing-openssl-to-segfault
 - SSL_shutdown
